import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  component: RouteComponent,
});

function RouteComponent() {
  return (
    <main className="w-full h-screen flex justify-center items-center bg-zinc-800 text-white">
      <div className="text-center space-y-2">
        <h1 className="text-xl font-bold">
          Welcome to the Vite + TanStack Router Template!
        </h1>
        <p>Generated by CalmUi</p>
      </div>
    </main>
  );
}
