function HomeModule() {
  return (
    <div className="text-center space-y-2">
      <h1 className="text-xl font-bold">
        Welcome to the Vite + TanStack Router Template!
      </h1>
      <p>Generated by CalmUi</p>
    </div>
  );
}

export default HomeModule;
